config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/jobs/new", to: "jobs#new"
  post "/jobs", to: "jobs#create"

  get "/jobs", to: "jobs#index"
  get "/jobs/:id", to: "jobs#show", as: "job"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(
      title: params[:job][:title],
      description: params[:job][:description],
      company: params[:job][:description]
    )
    if @job.save
      # success!
      redirect_to jobs_path
    else
      # failures!
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.html.erb
<h3>Jobs</h3>
<!-- <p>Jobs coming soon...</p> -->

<% @jobs.each do |job| %>
  <div class="job">
    <strong>
      <%= link_to job.title, job_path(job.id) %>
    </strong>
  </div>
<% end %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= form_for @job do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.label :company %>
  <%= f.text_field :company %>
  <br>
  <%= f.submit %>
<% end %>

app/views/jobs/show.html.erb
<h2>Job Details</h2>
<!-- <p>TODO: Add a real job</p> -->

<div>
  <strong><%= @job.title %></strong> at <%= @job.company %>
  <p><%= @job.description %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>